(function(root){
  'use strict';
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
  function mount(parent,model,{table,save}){
    const H=root.YouTrackHeatmap,A=root.YouTrackAdvanced,box=el('section',null,'advanced-card advanced-heatmap');box.id='advanced-heatmap';box.append(el('span','ФАКТИЧЕСКИЕ СПИСАНИЯ','analysis-eyebrow'),el('h3','Тепловая карта · участник × день'),el('p','Ячейка — списанные часы за день UTC. Пустая ячейка означает отсутствие списаний, а не свободное время.','advanced-caption'));
    const controls=el('div',null,'advanced-metric-controls'),select=(id,label,options)=>{const s=el('select');s.id=id;for(const [value,name]of options)s.append(new Option(name,value));const l=el('label',label);l.append(s);controls.append(l);return s;};
    const projects=[...new Set(model.rows.map(r=>r.project))],project=select('heatmap-project','Проект',[['all','Все проекты'],...projects.map(p=>[p,p])]),team=select('heatmap-team','Команда',[]),sort=select('heatmap-sort','Порядок участников',[['hours','Часы за окно ↓'],['name','По имени']]);const date=el('input');date.id='heatmap-date';date.type='date';date.value=date.min=model.from;date.max=model.to;const d=el('label','Начало окна · до 14 дней');d.append(date);controls.append(d);box.append(controls);
    let page=0,current;const body=el('div');box.append(body);parent.append(box);
    const choices=()=>{team.replaceChildren(new Option('Все команды','all'));for(const value of new Set(model.rows.filter(r=>project.value==='all'||r.project===project.value).map(r=>r.project+' / '+r.team)))team.append(new Option(value,value));};choices();
    const btn=(text,fn,disabled=false)=>{const b=el('button',text);b.type='button';b.disabled=disabled;b.addEventListener('click',fn);return b;};
    function draw(){
      if(!date.value||date.value<model.from||date.value>model.to)date.value=model.from;
      current=H.view(model,{project:project.value,team:team.value,start:date.value,page,sort:sort.value});page=current.page;body.replaceChildren();
      const shift=delta=>{date.value=new Date(Math.max(Date.parse(model.from),Math.min(Date.parse(model.to),Date.parse(date.value)+delta*86400000))).toISOString().slice(0,10);draw();};
      const nav=el('div',null,'sensor-pager');nav.append(btn('← 2 недели',()=>shift(-14),date.value===model.from),el('span',current.days[0]+' — '+current.days.at(-1)),btn('2 недели →',()=>shift(14),current.days.at(-1)===model.to));body.append(nav);
      const wrap=el('div',null,'heatmap-scroll'),grid=el('table',null,'heatmap-grid'),head=el('tr');head.append(el('th','Участник'));for(const day of current.days)head.append(el('th',day.slice(8)+'.'+day.slice(5,7)));const thead=el('thead');thead.append(head);grid.append(thead);const tbody=el('tbody'),detail=el('p','Нажмите ячейку, чтобы увидеть точное значение.','advanced-caption');detail.setAttribute('role','status');
      for(const row of current.rows){const tr=el('tr'),name=el('th',row.label);name.scope='row';tr.append(name);row.values.forEach((hours,i)=>{const td=el('td'),b=el('button',hours?A.fmt(hours):'—');b.type='button';const text=row.label+' · '+current.days[i]+' UTC · '+A.fmt(hours)+' ч';b.title=text;b.setAttribute('aria-label',text);const intensity=current.max?hours/current.max:0;b.style.background=hours?`rgba(105,72,178,${.15+.85*intensity})`:'#f4f4f8';b.style.color=intensity>.55?'#fff':'#342554';b.addEventListener('click',()=>{detail.textContent=text;});td.append(b);tr.append(td);});tbody.append(tr);}grid.append(tbody);wrap.append(grid);body.append(wrap,detail);
      if(!current.allCount)body.append(el('p','В выбранном составе нет участников.'));
      const pager=el('div',null,'sensor-pager');pager.append(btn('Предыдущие участники',()=>{page--;draw();},page===0),el('span',`${page+1} / ${current.pages} · участников: ${current.allCount}`),btn('Следующие участники',()=>{page++;draw();},page===current.pages-1));body.append(pager,el('p',`Светлее → темнее: меньше → больше часов в показанном окне. Максимум ${A.fmt(current.max)} ч. Это не шкала нагрузки. Все участники фильтра за окно: ${A.fmt(current.total)} ч.`,'advanced-caption'));
      body.append(btn('Скачать хитмап · PNG',()=>{const canvas=el('canvas');root.YouTrackSensorView.draw(current.chart,canvas);canvas.toBlob(blob=>blob&&save(blob,'sensor-heatmap.png'),'image/png');},!current.rows.length));
      const details=el('details');details.append(el('summary','Точные значения текущего окна'));let ready=false;details.addEventListener('toggle',()=>{if(!details.open||ready)return;ready=true;table(details,section());});body.append(details);
    }
    function section(){return {title:'Хитмап · текущее окно и участники',paragraphs:[current.chart.note,'Экспортируется показанное окно и страница участников. Отсутствие списания не доказывает отсутствие работы.'],headers:['Проект / команда / участник','Дата UTC','Часы'],rows:current.rows.flatMap(r=>r.values.map((h,i)=>({values:[r.label,current.days[i],A.fmt(h)]})))};}
    project.addEventListener('change',()=>{choices();page=0;draw();});for(const s of [team,sort,date])s.addEventListener('change',()=>{page=0;draw();});draw();root.YouTrackSensorHelp?.attach(box,'Как читать хитмап','Ячейка — сумма часов участника за день UTC. Цвет нормируется по максимуму видимого окна. Сравнивайте числа при смене окна. Участники разных проектов показаны отдельно. Ноль означает отсутствие списаний, а не свободную ёмкость. PNG и PDF сохраняют показанное окно и страницу участников.');
    return {snapshot:()=>({chart:structuredClone(current.chart),section:section(),summary:{title:'Хитмап · выбранное окно',paragraphs:[current.chart.note,'Показанное окно и страница участников; все точные ячейки — в CSV или PNG.'],headers:['Проект / команда / участник','Часы за окно','Дней со списаниями'],rows:current.rows.map(r=>({values:[r.label,A.fmt(r.total),String(r.values.filter(v=>v>0).length)]}))}})};
  }
  root.YouTrackHeatmapView={mount};
})(globalThis);
