(function(root){
  'use strict';
  const A=root.YouTrackAdvanced,NS='http://www.w3.org/2000/svg';
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
  const svg=(tag,attrs)=>{const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;};
  function mount(parent,trend,save){
    const panel=el('section',null,'advanced-card advanced-trend');panel.id='advanced-trend';parent.append(panel);
    panel.append(el('span','ВО ВРЕМЕНИ','analysis-eyebrow'),el('h3','Динамика списаний'),el('p','Меняйте окно и детализацию по уже загруженным данным. Новых запросов не будет.','advanced-caption'));
    const available=A.trendOptions(trend);let window='all',end=trend.to,current,selected=0;
    panel.append(el('p',`Собрано ${available.days} дней. Масштаб выбран автоматически: ${available.defaultGrain==='month'?'по месяцам':available.defaultGrain==='week'?'по неделям':'по дням'}. Ниже доступны только окна в пределах этой выборки.`,'advanced-caption'));
    const windows=el('div',null,'trend-windows');windows.setAttribute('role','group');windows.setAttribute('aria-label','Окно динамики');panel.append(windows);
    const buttons=[];for(const [value,label]of [['week','Неделя'],['fortnight','2 недели'],['month','Месяц'],['two-months','2 месяца'],['all','Весь период']].filter(([value])=>available.windows.includes(value))){const b=el('button',label);b.type='button';b.dataset.window=value;b.addEventListener('click',()=>{window=value;draw(true);});windows.append(b);buttons.push(b);}
    const controls=el('div',null,'trend-controls');
    function select(label,options,id){const l=el('label',label),s=el('select');s.id=id;for(const [v,t]of options)s.append(new Option(t,v));l.append(s);controls.append(l);s.addEventListener('change',draw);return s;}
    const grain=select('Группировка',[['day','По дням'],['week','По неделям · пн–вс'],['month','По месяцам']].filter(([value])=>available.grains.includes(value)),'trend-grain');grain.value=available.defaultGrain;
    const metric=select('Показатель',[['hours','Списано часов'],['items','Записей списаний']],'trend-metric');
    const category=select(trend.dimension==='activity'?'Вид работы':'Категория',[['all',trend.dimension==='activity'?'Все виды работ':'Все категории'],...Object.entries(trend.categories)],'trend-category');panel.append(controls);
    const paging=el('div',null,'trend-paging'),prev=el('button','← Раньше'),next=el('button','Позже →'),date=el('input'),dateLabel=el('label','Конец окна · UTC');prev.type=next.type='button';date.type='date';date.id='trend-end';date.min=trend.from;date.max=trend.to;date.value=end;dateLabel.append(date);paging.append(prev,dateLabel,next);panel.append(paging);
    prev.addEventListener('click',()=>{if(current.previousEnd){end=current.previousEnd;draw(true);}});next.addEventListener('click',()=>{if(current.nextEnd){end=current.nextEnd;draw(true);}});date.addEventListener('change',()=>{if(date.validity.valid&&date.value)end=date.value;draw(true);});
    const summary=el('p',null,'trend-summary');summary.setAttribute('role','status');const viewport=el('div',null,'trend-viewport'),detail=el('p',null,'trend-detail');detail.setAttribute('role','status');panel.append(summary,el('p','Прокрутите график вправо; нажмите точку, чтобы увидеть значение.','advanced-scroll-hint'),viewport,detail);
    const note='Даты списаний в UTC. Недели — понедельник–воскресенье; крайние интервалы могут быть неполными. Ноль означает отсутствие списаний в загруженной выборке, а не отсутствие работы. Тип задачи текущий: это не история оценок, статусов или ТТМ.';
    panel.append(el('p',note,'advanced-caption'));root.YouTrackSensorHelp?.attach(panel,'Динамика списаний','Для каждого дня суммируются duration.minutes / 60 и количество корректных уникальных work items. Далее дни объединяются по выбранным границам. '+(trend.dimension==='activity'?'Виды работ — точные workItem.type из YouTrack. Анализ, разработка и тестирование не объединяются. ':'Категории используют те же правила, что и блок «На что ушло время». ')+note);
    const download=el('button','Скачать динамику · PNG','advanced-text-button');download.type='button';download.id='trend-png';download.addEventListener('click',()=>{const canvas=document.createElement('canvas');canvas.width=1100;canvas.height=480;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,1100,480);c.fillStyle='#302541';c.font='bold 24px Arial';c.fillText('Динамика · '+category.options[category.selectedIndex].text,60,40);c.font='18px Arial';c.fillText(`${current.from} — ${current.to} · ${current.unit} · UTC`,60,72);const pts=points(current.rows,1000,290,60,112);c.strokeStyle='#7356c3';c.lineWidth=3;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();for(const p of pts){c.fillStyle='#7356c3';c.beginPath();c.arc(p.x,p.y,4,0,Math.PI*2);c.fill();}c.font='14px Arial';c.fillStyle='#57516a';pts.forEach((p,i)=>{if(i===0||i===pts.length-1||i%Math.max(1,Math.ceil(pts.length/6))===0)c.fillText(current.rows[i].from.slice(8)+'.'+current.rows[i].from.slice(5,7),Math.min(p.x,1025)-12,430);});c.fillText('0',25,407);c.fillText(A.fmt(Math.max(0,...current.rows.map(r=>r.value)))+' '+current.unit,18,105);c.fillText('Даты списаний. Крайние интервалы могут быть неполными.',60,466);canvas.toBlob(blob=>{if(blob)save(blob,'sensor-dynamics.png');});});panel.append(download);
    function points(rows,w,h,left,top){const max=Math.max(1,...rows.map(r=>r.value));return rows.map((r,i)=>({x:left+(rows.length===1?.5:i/(rows.length-1))*w,y:top+h-r.value/max*h}));}
    function draw(resetScale=false){
      if(window==='all')end=trend.to;
      const scope=A.trendView(trend,{window,end}),scales=A.trendOptions(scope),chosen=resetScale===true||!scales.grains.includes(grain.value)?scales.defaultGrain:grain.value;
      grain.replaceChildren();for(const [value,label]of [['day','По дням'],['week','По неделям · пн–вс'],['month','По месяцам']])if(scales.grains.includes(value))grain.append(new Option(label,value));grain.value=chosen;
      current=A.trendView(trend,{window,end,grain:grain.value,metric:metric.value,category:category.value});end=current.to;date.value=end;date.disabled=window==='all';prev.disabled=!current.previousEnd;next.disabled=!current.nextEnd;
      buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.window===window)));
      summary.textContent=`${current.from} — ${current.to} · ${A.fmt(current.total)} ${current.unit} · ${current.rows.length} интервалов${current.partial?' · окно ограничено загруженным периодом':''}`;
      viewport.replaceChildren();const graph=svg('svg',{viewBox:'0 0 1000 330',role:'group','aria-label':'Динамика '+metric.options[metric.selectedIndex].text});graph.classList.add('trend-svg');viewport.append(graph);const pts=points(current.rows,880,230,65,25),max=Math.max(1,...current.rows.map(r=>r.value));
      for(const part of [0,.5,1]){const y=255-part*230;graph.append(svg('line',{x1:65,x2:945,y1:y,y2:y,stroke:'#e7e2ee'}));const t=svg('text',{x:55,y:y+5,'text-anchor':'end',fill:'#625a71','font-size':14});t.textContent=A.fmt(max*part);graph.append(t);}
      graph.append(svg('polyline',{points:pts.map(p=>p.x+','+p.y).join(' '),fill:'none',stroke:'#7356c3','stroke-width':3}));
      const circles=[];function show(i){selected=i;const row=current.rows[i];detail.textContent=`${row.label}: ${A.fmt(row.value)} ${current.unit} · дней в интервале: ${row.days}`;circles.forEach((n,j)=>n.setAttribute('r',j===i?'7':'4'));}
      pts.forEach((p,i)=>{const row=current.rows[i],dot=svg('circle',{cx:p.x,cy:p.y,r:4,fill:'#7356c3',tabindex:0,role:'button','aria-label':`${row.label}: ${A.fmt(row.value)} ${current.unit}`});dot.addEventListener('pointerenter',()=>show(i));dot.addEventListener('focus',()=>show(i));dot.addEventListener('click',()=>show(i));dot.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?pts.length-1:Math.max(0,Math.min(pts.length-1,i+(e.key==='ArrowRight'?1:-1)));circles[n].focus();}else if(e.key==='Enter'||e.key===' '){e.preventDefault();show(i);}});graph.append(dot);circles.push(dot);
        if(i===0||i===pts.length-1||i%Math.max(1,Math.ceil(pts.length/7))===0){const t=svg('text',{x:p.x,y:285,'text-anchor':'middle',fill:'#625a71','font-size':14});t.textContent=row.from.slice(8)+'.'+row.from.slice(5,7);graph.append(t);}
      });if(pts.length)show(Math.min(selected,pts.length-1));
    }
    draw();return {snapshot(){const title='Динамика · '+category.options[category.selectedIndex].text+' · '+metric.options[metric.selectedIndex].text;return {section:{title,summary:`${current.from} — ${current.to} · UTC`,paragraphs:[`Выбранное окно: ${current.from} — ${current.to}. Группировка: ${grain.options[grain.selectedIndex].text}. ${note}`],headers:['Интервал','Дней',current.unit],rows:current.rows.map(r=>({values:[r.label,String(r.days),A.fmt(r.value)]}))},chart:{type:'bars',title,unit:current.unit,note:`${current.from} — ${current.to} · UTC`,rows:current.rows.map(r=>({label:r.label,values:[{value:r.value,color:'#7356c3'}]}))}};}};
  }
  root.YouTrackTrend={mount};
})(globalThis);
