(function(root){
  'use strict';
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
  function mount(parent,model,{table,poolLink,save}){
    const P=root.YouTrackPeople,A=root.YouTrackAdvanced,box=el('section',null,'advanced-card advanced-people');box.id='advanced-people';
    box.append(el('span','КОМАНДЫ → УЧАСТНИКИ','analysis-eyebrow'),el('h3','Разбор по составу teams.json'),el('p','Выберите команду, затем участника. Нажатие на имя в таблице открывает его показатели и динамику.','advanced-caption'));
    const controls=el('div',null,'people-controls'),team=el('select'),member=el('select'),view=el('select');team.id='people-team';member.id='people-member';view.id='people-view';
    const label=(s,n)=>{const l=el('label',s);l.append(n);return l;};team.append(new Option('Все команды',''));for(const t of model.teams)team.append(new Option(t.displayName||t.name,t.id));
    for(const [v,s]of [['activities','Виды работ · анализ / разработка / тестирование'],['hours','Категории первого отчёта'],['delivery','Закрытие и оценка разработки'],['capacity','Ёмкость команд']])view.append(new Option(s,v));
    controls.append(label('Команда',team),label('Участник',member),label('Показатели',view));box.append(controls);
    const summary=el('div',null,'advanced-kpis'),note=el('p',null,'advanced-caption'),body=el('div'),chart=el('div',null,'advanced-bars'),personal=el('div'),capacity=el('div',null,'people-capacity-grid');box.append(summary,capacity,note,body,chart,personal);parent.append(box);
    function memberChoices(){member.replaceChildren(new Option('Все участники',''));const t=model.teams.find(t=>t.id===team.value);for(const m of t?.members||[])member.append(new Option(m.login,m.login));member.disabled=!t;}
    function draw(){
      summary.replaceChildren();capacity.replaceChildren();body.replaceChildren();personal.replaceChildren();chart.replaceChildren();
      const t=model.teams.find(t=>t.id===team.value),m=t?.members.find(m=>m.login===member.value),target=m||t,group=t?[t]:model.teams;
      const total=target?target.totalHours:group.reduce((n,t)=>n+t.totalHours,0),closed=target?target.stats.closedFeatures:group.reduce((n,t)=>n+t.stats.closedFeatures,0),count=target?target.issueIds.length:null;
      for(const [title,value,caption]of [['Списано',A.fmt(total)+' ч','Все категории, включая нераспознанные'],['Закрытые БЗ',String(closed),target?'С бизнес-списаниями в периоде':'Сумма командных показателей'],['Состав',m?m.login:String(group.reduce((n,t)=>n+t.members.length,0)),m?t.name:'Участников, включая нулевые списания'],['Задачи',count==null?'По командам':String(count),'Точные подборки доступны в таблице']]){const card=el('article',null,'advanced-kpi');card.append(el('span',title),el('strong',value),el('p',caption));summary.append(card);}
      for(const teamModel of group){const c=P.capacity(teamModel),card=el('article',null,'people-capacity-card'),ring=el('div',null,'people-capacity-ring'),inside=el('div'),info=el('div');ring.style.setProperty('--capacity-fill',c.fill+'%');ring.style.setProperty('--capacity-color',c.excess>0?'#a85d17':'#7356c3');ring.setAttribute('role','img');ring.setAttribute('aria-label','Бизнес-ёмкость: '+(c.percent==null?'не задана':A.fmt(c.percent)+'%'));inside.append(el('strong',c.percent==null?'—':A.fmt(c.percent)+'%'),el('span',c.percent==null?'нет ёмкости':'использовано'));ring.append(inside);info.append(el('h4',teamModel.displayName||teamModel.name),el('p',c.percent==null?'Бизнес-ёмкость не задана или равна нулю. Процент не рассчитывается.':A.fmt(c.hours)+' из '+A.fmt(c.limit)+' ч бизнес-ёмкости'),el('p',c.excess>0?'Сверх ёмкости: '+A.fmt(c.excess)+' ч':'Бизнес-списания / ёмкость из teams.json. Значение ёмкости должно соответствовать периоду.','advanced-caption'));card.append(ring,info);capacity.append(card);}
      note.textContent=m?`${m.login}: ${m.activeDays} дней со списаниями; ${A.fmt(m.unclassifiedHours)} ч не распознано. ${m.totalHours===0?'Списаний нет — это не оценка доступности.':''}`:t?`${t.members.length} участников. Часы и оценки рассчитаны тем же модулем, что в первом отчёте.`:'Сводка команд. Выберите команду или нажмите её название для перехода к участникам.';
      let headers,rows;const targets=m?[{team:t,x:m}]:t?t.members.map(x=>({team:t,x})):group.map(x=>({team:x,x}));
      const make=(xteam,x,values)=>({poolKey:x.poolKey,values,open:()=>{if(x===xteam){team.value=xteam.id;memberChoices();}else member.value=x.login;draw();}});
      if(view.value==='activities'){headers=[t?'Участник':'Команда','Все часы',...Object.values(model.activities).map(k=>k+', ч')];rows=targets.map(({team:t,x})=>make(t,x,[x.login||x.displayName||x.name,A.fmt(x.totalHours),...Object.keys(model.activities).map(k=>A.fmt(x.activities[k].hours))]));note.textContent='Каждый столбец — отдельный вид workItem.type из YouTrack. Анализ, разработка и тестирование не объединяются. Значения не переименовываются по догадке.';}
      else if(view.value==='hours'){headers=[t?'Участник':'Команда','Все часы',...P.keys.map(k=>model.labels[k]+', ч'),'Вне этих категорий, ч'];rows=targets.map(({team:t,x})=>make(t,x,[x.login||x.displayName||x.name,A.fmt(x.totalHours),...P.keys.map(k=>A.fmt(x.stats[k])),A.fmt(x.unclassifiedHours)]));note.textContent='Категории первого отчёта определяются типом задачи и настроенными типами списаний. Анализ и тестирование, не включённые в эти правила, смотрите в «Виды работ».';}
      else if(view.value==='delivery'){headers=[t?'Участник':'Команда','Закрытые БЗ','В оценке','С оценкой','Выше оценки','Среднее факт/оценка, %'];rows=targets.map(({team:t,x})=>make(t,x,[x.login||x.displayName||x.name,String(x.stats.closedFeatures),String(x.stats.estimateHits),String(x.stats.estimateTotal),String(x.stats.estimateTotal-x.stats.estimateHits),A.fmt(x.stats.estimateAveragePct)]));}
      else {headers=['Команда','Бизнес, ч','Ёмкость, ч','Использовано, %'];rows=group.map(t=>make(t,t,[t.displayName||t.name,A.fmt(t.stats.business),A.fmt(t.capacityHours),t.capacityHours>0?A.fmt(t.stats.business/t.capacityHours*100):'Нет данных']));note.textContent='Ёмкость из teams.json должна соответствовать выбранному периоду. Использовано = бизнес-часы / бизнес-ёмкость × 100%. Индивидуальная доступность из этого не определяется.';}
      if(m&&m.totalHours===0)note.textContent+=' Списаний нет — это не оценка доступности.';
      table(body,{title:'Команды и участники',headers,rows});
      const ranked=targets.slice().sort((a,b)=>b.x.totalHours-a.x.totalHours).slice(0,8),max=Math.max(1,...ranked.map(v=>v.x.totalHours));chart.append(el('h4',view.value==='activities'?'Виды работ · часы':m?'Категории участника':t?'Списания участников · первые 8':'Списания команд · первые 8'));
      const bars=view.value==='activities'?Object.entries(model.activities).map(([k,label])=>({label,value:targets.reduce((n,v)=>n+v.x.activities[k].hours,0)})):m?P.keys.map(k=>({label:model.labels[k],value:m.stats[k]})):ranked.map(v=>({label:v.x.login||v.x.displayName||v.x.name,value:v.x.totalHours}));const scale=m||view.value==='activities'?Math.max(1,...bars.map(b=>b.value)):max;
      for(const b of bars){const row=el('div',null,'advanced-bar-row'),caption=el('div',null,'advanced-bar-label'),track=el('div',null,'advanced-bar-track'),fill=el('div');caption.append(el('span',b.label),el('strong',A.fmt(b.value)+' ч'));fill.style.width=b.value/scale*100+'%';track.append(fill);row.append(caption,track);chart.append(row);}
      const png=el('button','Скачать сравнение · PNG','advanced-text-button');png.type='button';png.addEventListener('click',()=>{const canvas=el('canvas');root.YouTrackSensorView.draw({type:'bars',title:view.value==='activities'?'Виды работ · '+(m?m.login:t?t.displayName||t.name:'все команды'):m?m.login+' · категории':t?t.name+' · участники':'Команды · списания',unit:'ч',note:model.from+' — '+model.to,rows:bars.map(b=>({label:b.label,values:[{value:b.value,color:'#7356c3'}]}))},canvas);canvas.toBlob(blob=>{if(blob)save(blob,'sensor-people.png');},'image/png');});chart.append(png);
      if(target){const link=target.poolKey&&poolLink(target.poolKey);if(link)personal.append(link);root.YouTrackTrend.mount(personal,P.trend(model,target),save);personal.querySelector('h3').textContent='Динамика · '+(m?m.login:t.name);personal.querySelector('#trend-category').parentElement.firstChild.textContent='Вид работы';for(const n of personal.querySelectorAll('[id]'))n.id='people-'+n.id;}
    }
    team.addEventListener('change',()=>{memberChoices();draw();});member.addEventListener('change',draw);view.addEventListener('change',draw);memberChoices();draw();
    root.YouTrackSensorHelp?.attach(box,'Команды и участники',model.method);
  }
  root.YouTrackPeopleView={mount};
})(globalThis);
